### ISSUE TITLE
Dataset insert

### ISSUE THREAD

**Issue by Dawido090** [dullroar/fuzzy-examples#1]
Hi Jim,
We both know you provided simple data model within book, but could you please provide actual inserts and table/views declaration?
Tried to do copy-paste with chat-gpt, but failed to provide exact set of data which is extremly important to understand your craft with parsing.

**Comment by dullroar** [comment]
Most reasonable request. Am working on it right now. Stay tuned.

**Comment by dullroar** [comment]
Fixed with commit 781570381e7ea3a485f993d5cbb8187077b9fba4.
